import {Player} from '@remotion/player';
import {ArrowLeft, CheckCircle2, Copy, FolderOpen, ImagePlus, Loader2, Palette, Plus, RefreshCw, Save, Undo2, Redo2} from 'lucide-react';
import {BlankPoster} from '../../../packages/studio-runtime/src/BlankPoster';
import {studioApi} from './studioApi';
import StudioSourcePreview from './StudioSourcePreview';
import StudioLayersPanel from './StudioLayersPanel';
import StudioHistoryPanel from './StudioHistoryPanel';
import {useStudioEditor} from './useStudioEditor';
import type {Fields} from './studioEditorSettings';
import {useRef} from 'react';
import {useMediaTransfer} from '@/hooks/useMediaTransfer';
import StudioExportPanel from './StudioExportPanel';
import StudioBundleDownload from './StudioBundleDownload';

const inputClass = 'mt-1 w-full rounded-lg border border-white/10 bg-[#121318] px-3 py-2 text-sm text-white focus:border-purple-400 focus:outline-none';
const buttonClass = 'inline-flex items-center justify-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-sm text-gray-200 hover:bg-white/5 disabled:cursor-not-allowed disabled:opacity-40';
const primaryClass = `${buttonClass} border-purple-400/40 bg-purple-500/20 text-purple-100 hover:bg-purple-500/30`;
function SettingsFields({fields, onChange, disabled, creating = false}: {fields: Fields; onChange: (fields: Fields) => void; disabled: boolean; creating?: boolean}) {
  const update = (key: keyof Fields, value: string) => onChange({...fields, [key]: value});
  return <div className="space-y-3">
    <label className="block text-xs text-gray-400">프로젝트 이름<input aria-label={creating ? '새 프로젝트 이름' : '프로젝트 이름'} maxLength={80} value={fields.name} disabled={disabled} onChange={(event) => update('name', event.target.value)} className={inputClass} /></label>
    <div className="grid grid-cols-2 gap-3">
      <label className="text-xs text-gray-400">가로 (px)<input aria-label={creating ? '새 캔버스 가로' : '캔버스 가로'} type="number" min={64} max={8192} step={1} value={fields.width} disabled={disabled} onChange={(event) => update('width', event.target.value)} className={inputClass} /></label>
      <label className="text-xs text-gray-400">세로 (px)<input aria-label={creating ? '새 캔버스 세로' : '캔버스 세로'} type="number" min={64} max={8192} step={1} value={fields.height} disabled={disabled} onChange={(event) => update('height', event.target.value)} className={inputClass} /></label>
      <label className="text-xs text-gray-400">FPS<input aria-label={creating ? '새 프로젝트 FPS' : '프로젝트 FPS'} type="number" min={1} max={60} step={1} value={fields.fps} disabled={disabled} onChange={(event) => update('fps', event.target.value)} className={inputClass} /></label>
      <label className="text-xs text-gray-400">길이 (초)<input aria-label={creating ? '새 프로젝트 길이' : '프로젝트 길이'} type="number" min={0.0167} max={18000} step="any" value={fields.seconds} disabled={disabled} onChange={(event) => update('seconds', event.target.value)} className={inputClass} /></label>
    </div>
    {!creating && <label className="block text-xs text-gray-400">캔버스 배경<input aria-label="캔버스 배경" type="color" value={fields.backgroundColor} disabled={disabled} onChange={(event) => update('backgroundColor', event.target.value)} className="mt-1 h-9 w-full rounded-lg border border-white/10 bg-[#121318] p-1" /></label>}
  </div>;
}

export default function StudioPanel({isActive}: {isActive: boolean}) {
  const bundleInput = useRef<HTMLInputElement>(null);
  const {controller: mediaTransfer} = useMediaTransfer();
  const {
    projects, project, fields, setFields, newFields, setNewFields, creating, setCreating, connected, busy,
    status, error, selectedAsset, setSelectedAsset, frame, runtimeStatus, remoteProject, sourcePreview,
    aiRequest, setAiRequest, copyStatus, setCopyStatus, layerDraft, selectedLayer, layerGeometry, editMode,
    setEditMode, layerNotice, draftNotice, dirty, registry, previewComposition, previewEdits, inspectorDisabled,
    editingDisabled, asset, requestText, pendingWrite, recovery, versionHistory, selectedVersion, playerRef,
    assetInput, connect, openProject, reopenProject, createProject, startCreating, save, addAssets, compile,
    copyRequest, selectLayer, changeLayer, measureLayers, updateSourceFrame, reportPreviewError, reorderLayer,
    adoptRemote, undo, redo, canUndo, canRedo, beginInteraction, endInteraction, registerCancel, keyboardShortcut,
    refreshHistory, selectVersion, restoreVersion, restoreRecovery, hasDraft, importProject,
  } = useStudioEditor(isActive);
  const previewDocument = project;
  const fieldTarget = (target: EventTarget) => target instanceof HTMLElement && Boolean(target.closest('input,textarea,select'));
  const lastMcpSeen = runtimeStatus?.mcp.lastSeenAt ? Date.parse(runtimeStatus.mcp.lastSeenAt) : NaN;
  const lastMcpTool = runtimeStatus?.mcp.lastToolAt ? Date.parse(runtimeStatus.mcp.lastToolAt) : NaN;
  const mcpRecent = connected && Number.isFinite(lastMcpSeen) && Date.now() - lastMcpSeen >= 0 && Date.now() - lastMcpSeen < 90000;
  const compileLabels = {idle: '소스 컴파일 대기', compiling: '소스 컴파일 중…', ready: '소스 미리보기 준비됨', failed: '소스 컴파일 실패'};

  return <section onKeyDownCapture={keyboardShortcut} aria-label="포스터 메이커" className="relative space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div><p className="flex items-center gap-2 text-xs text-purple-300"><Palette size={15} /> 포스터 · 홍보지</p><h2 className="mt-2 text-2xl font-semibold text-white">포스터 메이커</h2><p className="mt-2 text-sm text-gray-400">빈 캔버스에서 시작하고, 이미지와 프로젝트를 이 컴퓨터에 보관하세요.</p></div>
      <button className={buttonClass} disabled={busy} onClick={() => void connect(!project)}><RefreshCw size={14} className={busy ? 'animate-spin' : ''} />{connected ? '연결 확인' : '다시 연결'}</button>
    </div>
    <div className="flex flex-wrap items-center gap-3 text-xs text-gray-400" role="status"><span className={`inline-flex items-center gap-2 ${connected ? 'text-green-300' : 'text-amber-200'}`}><span className={`h-2 w-2 rounded-full ${connected ? 'bg-green-400' : 'bg-amber-400'}`} />{connected ? '로컬 서비스 연결됨' : '로컬 서비스 연결 필요'}</span><span>{busy ? '처리 중…' : status}</span></div>
    {!connected && <div className="rounded-xl border border-purple-400/20 bg-purple-500/5 p-4 text-sm text-gray-300"><p>이 컴퓨터에서 프로젝트 저장 서비스를 실행하세요.</p><code className="mt-2 block select-all rounded-lg bg-black/25 p-3 text-xs text-purple-200">npm run studio:server</code>{window.location.protocol === 'https:' && <p className="mt-3 text-xs leading-relaxed text-gray-300">이 사이트의 로컬 네트워크 접근 권한을 확인한 뒤 다시 연결하세요. 미리보기 배포 주소는 서비스의 STUDIO_ALLOWED_ORIGIN에 정확히 등록해야 합니다. 내장 브라우저에서 연결 권한을 확인할 수 없으면 <a href="http://127.0.0.1:5173/?studio=1" target="_blank" rel="noopener noreferrer" className="text-purple-300 underline">로컬 포스터 메이커</a>를 사용하세요.</p>}<p className="mt-2 text-xs text-gray-400">현재 입력은 이 탭에 보관됩니다. 로컬 편집은 계속할 수 있고, 저장·파일 추가·버전 복원은 다시 연결한 뒤 사용할 수 있습니다.</p></div>}
    {error && <p role="alert" className="whitespace-pre-line rounded-xl border border-amber-400/20 bg-amber-400/5 p-3 text-sm text-amber-200">{error}</p>}
    {draftNotice && <p role="status" className="rounded-lg border border-amber-400/20 p-3 text-xs text-amber-200">{draftNotice}</p>}
    <div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
      <aside className="space-y-4 rounded-xl border border-white/10 bg-black/15 p-4" aria-label="저장된 프로젝트">
        <div className="flex items-center gap-2 text-sm font-semibold text-white"><FolderOpen size={16} />내 프로젝트</div>
        <button className={`${primaryClass} w-full`} disabled={!connected || busy} onClick={startCreating}><Plus size={15} />새 프로젝트</button>
        <button className={`${buttonClass} w-full`} disabled={!connected || busy} onClick={() => bundleInput.current?.click()}><FolderOpen size={15} />프로젝트 파일 가져오기</button>
        <input ref={bundleInput} type="file" accept=".vyvyd.json,.json,application/json" aria-label="가져올 프로젝트 파일" className="sr-only" onChange={(event) => {const file = event.target.files?.[0]; event.target.value = ''; if (file) void importProject(file);}} />
        {projects.length === 0 && <p className="text-xs leading-relaxed text-gray-500">아직 프로젝트가 없습니다. 새 프로젝트로 시작하세요.</p>}
        <div className="max-h-96 space-y-2 overflow-auto">{projects.map((entry) => <button key={entry.id} className={`w-full rounded-lg border p-3 text-left disabled:opacity-40 ${project?.id === entry.id && !creating ? 'border-purple-400/40 bg-purple-500/10' : 'border-white/5 hover:bg-white/5'}`} disabled={busy} aria-label={`프로젝트 열기: ${entry.name}`} onClick={() => void openProject(entry.id)}><span className="block truncate text-sm text-gray-200">{entry.name}</span><span className="mt-1 block text-[11px] text-gray-500">{entry.composition.width} × {entry.composition.height} · 파일 {entry.assetCount}개{(project?.id === entry.id ? dirty : hasDraft(entry.id)) && <span className="ml-2 text-amber-200">초안 있음</span>}</span></button>)}</div>
      </aside>
      {creating ? <div className="rounded-xl border border-white/10 p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold text-white">빈 프로젝트 만들기</h3><button className={buttonClass} disabled={busy} onClick={() => setCreating(false)}><ArrowLeft size={14} />돌아가기</button></div><SettingsFields fields={newFields} onChange={setNewFields} disabled={busy} creating /><p className="mt-3 text-xs text-gray-500">디자인이 없는 빈 캔버스로 시작합니다. 길이는 FPS에 맞는 프레임 수로 저장됩니다.</p><button className={`${primaryClass} mt-5`} disabled={busy || !connected} onClick={() => void createProject()}>{busy ? <Loader2 size={15} className="animate-spin" /> : <Plus size={15} />}프로젝트 만들기</button></div>
      : project && previewComposition ? <div className="min-w-0 space-y-5">
        <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">{project.name}</h3><p className="mt-1 text-xs text-gray-500">{dirty ? `미저장 변경 있음 · 기준 버전 ${project.revision}` : `저장됨 · 버전 ${project.revision}`}</p><p className="mt-1 select-all break-all font-mono text-[11px] text-gray-500">프로젝트 ID: {project.id}</p></div><div className="flex gap-2"><button className={buttonClass} disabled={busy || !connected} onClick={() => void reopenProject()}><FolderOpen size={14} />저장본 다시 열기</button><button className={primaryClass} disabled={busy || !connected || !dirty || Boolean(remoteProject) || Boolean(pendingWrite)} onClick={() => void save()}><Save size={14} />저장</button></div></div>
        {pendingWrite && <div role={busy ? "status" : "alert"} className="rounded-xl border border-amber-400/25 p-4 text-sm text-amber-200"><p>{busy ? pendingWrite.kind === "restore" ? "선택한 버전의 소스를 검증하고 복원하고 있습니다…" : "현재 편집을 저장하고 있습니다…" : "저장 결과를 아직 확인하지 못했습니다. 현재 입력과 요청을 보관했습니다."}</p><p className="mt-1 text-xs text-gray-400">다시 연결하면 저장 여부를 확인합니다. 같은 요청을 재시도해도 저장 버전은 중복으로 추가되지 않습니다.</p><button className={`${buttonClass} mt-3`} disabled={busy || !connected} onClick={() => void save(true)}>같은 요청 다시 시도</button></div>}
        <div className="flex flex-wrap items-center gap-2" aria-label="편집 이력"><button className={buttonClass} disabled={busy || Boolean(remoteProject) || !canUndo} onClick={undo} title="Ctrl/⌘+Z"><Undo2 size={14} />되돌리기</button><button className={buttonClass} disabled={busy || Boolean(remoteProject) || !canRedo} onClick={redo} title="Ctrl/⌘+Shift+Z 또는 Ctrl+Y"><Redo2 size={14} />다시 실행</button><span className="text-xs text-gray-500">드래그 한 번은 한 단계 · 저장 버전 복원은 아래 이력에서</span></div>
        {remoteProject && <div role="alert" className="rounded-xl border border-amber-400/25 bg-amber-400/5 p-4 text-sm text-amber-200"><p>저장본이 버전 {remoteProject.revision}로 변경되었습니다. 현재 입력을 유지했고 자동으로 덮어쓰지 않았습니다.</p><p className="mt-1 text-xs text-gray-400">현재 미리보기를 유지했습니다. 최신 저장본을 다시 읽거나, 변경한 입력만 최신 버전에 적용한 뒤 확인하세요.</p><div className="mt-3 flex flex-wrap gap-2"><button className={buttonClass} disabled={busy || !connected || Boolean(pendingWrite)} onClick={() => void reopenProject()}>최신 저장본 다시 읽기</button><button className={buttonClass} disabled={busy || Boolean(pendingWrite)} onClick={adoptRemote}>내 입력 유지하고 최신 버전 사용</button></div></div>}
        <div className="rounded-xl border border-white/10 bg-black/15 p-4" aria-label="Codex 연결과 소스 상태"><div className="flex flex-wrap items-start justify-between gap-3"><div className="space-y-1.5 text-xs"><p className={mcpRecent ? 'text-green-300' : 'text-gray-400'}>{mcpRecent ? 'MCP 최근 연결' : Number.isFinite(lastMcpSeen) ? 'MCP 최근 사용 없음' : 'MCP 연결 대기'}{runtimeStatus?.mcp.clientName && ` · ${runtimeStatus.mcp.clientName}`}</p>{Number.isFinite(lastMcpSeen) && <p className="text-gray-500">최근 연결 확인: {new Date(lastMcpSeen).toLocaleString('ko-KR')}</p>}{Number.isFinite(lastMcpTool) ? <p className="text-gray-500">마지막 도구 호출: {new Date(lastMcpTool).toLocaleString('ko-KR')}</p> : <p className="text-gray-500">MCP 도구 호출 대기</p>}<p className={runtimeStatus?.compile.state === 'failed' ? 'text-amber-200' : 'text-purple-200'}>{runtimeStatus ? compileLabels[runtimeStatus.compile.state] : '소스 상태 확인 중…'}{sourcePreview && ` · 표시 버전 ${sourcePreview.revision}`}</p><p className="text-gray-500">로컬 서비스 연결과 MCP 도구 사용 상태를 따로 확인합니다.</p></div><button className={buttonClass} disabled={busy || !connected || runtimeStatus?.compile.state === 'compiling'} onClick={() => void compile()}><RefreshCw size={14} className={runtimeStatus?.compile.state === 'compiling' ? 'animate-spin' : ''} />소스 다시 컴파일</button></div>{runtimeStatus?.compile.state === 'failed' && <pre role="alert" className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-black/25 p-3 text-xs text-amber-200">{runtimeStatus.compile.message || '소스를 컴파일하지 못했습니다.'}{sourcePreview ? '\n마지막 정상 소스 미리보기를 유지했습니다.' : '\n빈 캔버스 미리보기를 유지했습니다.'}</pre>}</div>
        <StudioHistoryPanel project={project} history={versionHistory} selected={selectedVersion} busy={busy} connected={connected} dirty={dirty} conflicted={Boolean(remoteProject) || Boolean(pendingWrite)} onRefresh={() => void refreshHistory()} onSelect={(revision) => void selectVersion(revision)} onRestore={() => void restoreVersion()} />
        {recovery && <div className="flex flex-wrap items-center gap-3 rounded-lg border border-purple-400/20 p-3"><p className="text-xs text-gray-400">복원·소스 변경 전의 미저장 입력을 보관했습니다.</p><button className={buttonClass} disabled={busy || Boolean(remoteProject) || Boolean(pendingWrite)} onClick={restoreRecovery}>이전 입력 가져오기</button></div>}
        {layerNotice && <p role="status" className="rounded-lg border border-amber-400/20 p-3 text-xs text-amber-200">{layerNotice}</p>}
        <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-black/15 p-3">
          <div className="flex gap-2"><button className={editMode ? primaryClass : buttonClass} aria-pressed={editMode} onClick={() => setEditMode(true)}>레이어 편집</button><button className={!editMode ? primaryClass : buttonClass} aria-pressed={!editMode} onClick={() => setEditMode(false)}>재생 보기</button></div>
          {sourcePreview && <label className="flex items-center gap-2 text-xs text-gray-400">프레임<input aria-label="편집 프레임" type="range" min={0} max={previewComposition.durationInFrames - 1} value={Math.min(frame, previewComposition.durationInFrames - 1)} disabled={!editMode || busy} onChange={(event) => updateSourceFrame(Number(event.target.value), true)} className="w-32 accent-purple-400" /><span className="tabular-nums">{frame}</span></label>}
          <p className="w-full text-xs text-gray-500">편집 모드에서 레이어를 선택하고 드래그하세요. 방향키 1px · Shift+방향키 10px. 변경 후 저장하면 Codex와 공유됩니다.</p>
          {registry.length > 0 && editingDisabled && !busy && <p className="text-xs text-amber-200">{remoteProject ? '외부 변경을 확인한 뒤 편집을 이어가세요.' : '저장한 버전의 소스 미리보기를 준비한 뒤 직접 편집할 수 있습니다.'}</p>}
        </div>
        <div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_270px]">
          <div className="min-w-0"><div className="flex min-h-64 items-center justify-center overflow-hidden rounded-xl border border-white/10 bg-[#0a0b10] p-4" data-testid="studio-canvas">{sourcePreview?.projectId === project.id && previewDocument ? <StudioSourcePreview projectId={project.id} revision={sourcePreview.revision} previewUrl={sourcePreview.url} composition={previewComposition} edits={previewEdits} frame={frame} isActive={isActive} onFrame={updateSourceFrame} onError={reportPreviewError} registry={registry} selectedLayerId={selectedLayer} editMode={editMode} editingDisabled={editingDisabled} onSelectLayer={selectLayer} onChangeLayer={changeLayer} onMeasured={measureLayers} onBeginInteraction={beginInteraction} onEndInteraction={endInteraction} onRegisterCancelInteraction={registerCancel} /> : <Player key={`${project.id}-${previewComposition.width}-${previewComposition.height}-${previewComposition.fps}-${previewComposition.durationInFrames}`} ref={playerRef} component={BlankPoster} inputProps={{backgroundColor: fields.backgroundColor, composition: previewComposition}} durationInFrames={previewComposition.durationInFrames} fps={previewComposition.fps} compositionWidth={previewComposition.width} compositionHeight={previewComposition.height} initialFrame={Math.min(frame, previewComposition.durationInFrames - 1)} controls loop spaceKeyToPlayOrPause={isActive} style={{width: '100%', maxWidth: Math.min(560, 520 * previewComposition.width / previewComposition.height), aspectRatio: `${previewComposition.width}/${previewComposition.height}`}} errorFallback={({error: cause}) => <p className="p-4 text-sm text-amber-200">미리보기 오류: {cause.message}</p>} />}</div><div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-xs text-gray-500"><span>{previewComposition.width} × {previewComposition.height} · {previewComposition.fps} FPS · {(previewComposition.durationInFrames / previewComposition.fps).toFixed(2)}초{dirty ? ' · 미저장 변경 반영' : ''}</span><span>프레임 {frame} / {previewComposition.durationInFrames - 1}</span></div></div>
          <div className="space-y-4" onFocusCapture={(event) => {if (fieldTarget(event.target)) beginInteraction();}} onBlurCapture={(event) => {if (fieldTarget(event.target)) endInteraction();}}><StudioLayersPanel key={`${project.id}-${project.revision}`} registry={registry} edits={layerDraft} assets={project.assets} selectedId={selectedLayer} onSelect={selectLayer} onChange={changeLayer} disabled={inspectorDisabled} measured={editingDisabled ? [] : layerGeometry} onReorder={reorderLayer} /><aside className="rounded-xl border border-white/10 bg-black/15 p-4" aria-label="프로젝트 설정"><details><summary className="cursor-pointer text-sm font-semibold text-white">프로젝트 설정</summary><div className="mt-4"><SettingsFields fields={fields} onChange={setFields} disabled={inspectorDisabled} /><p className="mt-3 text-xs leading-relaxed text-gray-500">설정·레이어 변경은 저장으로 반영합니다. 이미지 파일은 추가 즉시 보관됩니다.</p></div></details></aside></div>
        </div>
        <div className="rounded-xl border border-white/10 p-4" aria-label="프로젝트 파일"><div className="flex flex-wrap items-center justify-between gap-3"><h4 className="text-sm font-semibold text-white">파일 <span className="text-gray-500">{previewDocument!.assets.length}</span></h4><button className={buttonClass} disabled={busy || !connected || Boolean(remoteProject) || Boolean(pendingWrite)} onClick={() => assetInput.current?.click()}><ImagePlus size={15} />이미지 추가</button><input ref={assetInput} type="file" aria-label="프로젝트 이미지 파일" accept="image/png,image/jpeg,image/webp,image/gif" multiple className="sr-only" onChange={(event) => void addAssets(Array.from(event.target.files ?? []))} /></div><p className="mt-2 text-xs text-gray-500">PNG · JPG · WebP · GIF, 파일당 20 MB 이하. 추가한 파일은 프로젝트에 보관됩니다.</p>{previewDocument!.assets.length === 0 ? <p className="py-8 text-center text-sm text-gray-500">이미지나 로고를 추가하세요.</p> : <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{previewDocument!.assets.map((entry) => <button key={entry.id} aria-label={`파일 보기: ${entry.name}`} className={`overflow-hidden rounded-lg border text-left ${selectedAsset === entry.id ? 'border-purple-400' : 'border-white/10 hover:border-white/25'}`} onClick={() => setSelectedAsset(entry.id)}><img src={studioApi.assetUrl(project.id, entry.id)} alt={entry.name} className="h-24 w-full bg-[#121318] object-contain" /><span className="block truncate px-2 pt-2 text-xs text-gray-300">{entry.name}</span><span className="block px-2 pb-2 pt-1 text-[11px] text-gray-500">{(entry.size / 1024).toFixed(1)} KB</span></button>)}</div>}{asset && <div className="mt-4 rounded-lg bg-black/15 p-3"><p className="mb-3 text-xs text-gray-400">파일 미리보기 · {asset.name}</p><img src={studioApi.assetUrl(project.id, asset.id)} alt={`파일 미리보기: ${asset.name}`} className="max-h-72 w-full object-contain" /></div>}</div>
        <div className="rounded-xl border border-purple-400/20 bg-purple-500/5 p-4" aria-label="현재 Codex에 작업 요청"><h4 className="text-sm font-semibold text-purple-100">현재 Codex에 작업 요청</h4><p className="mt-2 text-xs leading-relaxed text-gray-400">원하는 작업을 적고 요청 문구를 복사해 현재 대화에 붙여넣으세요. Codex의 소스 수정은 이 미리보기에 자동 반영됩니다.</p><label className="mt-3 block text-xs text-gray-400">원하는 작업<textarea aria-label="Codex에 요청할 작업" value={aiRequest} onChange={(event) => {setAiRequest(event.target.value); setCopyStatus('');}} placeholder="예: 추가한 이미지를 사용하고 제목에 자연스러운 등장 애니메이션을 넣어 주세요." className={`${inputClass} min-h-24`} /></label><button type="button" className={`${primaryClass} mt-3`} onClick={() => void copyRequest()}><Copy size={14} />프로젝트 요청 문구 복사</button>{copyStatus && <p role="status" className="mt-2 text-xs text-purple-200">{copyStatus}</p>}<details className="mt-3 text-xs text-gray-400"><summary className="cursor-pointer">복사 내용 보기</summary><textarea readOnly aria-label="Codex 요청 복사 내용" value={requestText} onFocus={(event) => event.target.select()} className={`${inputClass} min-h-48 font-mono text-xs`} /></details></div>
        <StudioExportPanel project={project} frame={frame} dirty={dirty} connected={connected} onUseVideo={(result) => mediaTransfer.transfer('video', [result])} />
        <StudioBundleDownload project={project} connected={connected} dirty={dirty} />
        <details className="rounded-xl border border-white/10 p-4 text-xs text-gray-500"><summary className="cursor-pointer text-gray-400">프로젝트 정보</summary><dl className="mt-3 space-y-2 break-all"><div><dt>프로젝트 ID</dt><dd className="select-all font-mono">{project.id}</dd></div><div><dt>소스 파일</dt><dd>{Object.keys(previewDocument!.source.files).join(', ')}</dd></div><div><dt>마지막 저장</dt><dd>{new Date(previewDocument!.updatedAt).toLocaleString('ko-KR')}</dd></div></dl></details>
      </div> : <div className="flex min-h-96 flex-col items-center justify-center rounded-xl border border-dashed border-white/10 p-8 text-center"><Palette size={32} className="text-purple-300" /><h3 className="mt-4 text-lg font-semibold text-white">첫 포스터를 시작하세요</h3><p className="mt-2 max-w-sm text-sm leading-relaxed text-gray-400">캔버스 크기를 정하고 이미지·로고를 보관할 프로젝트를 만드세요.</p><button className={`${primaryClass} mt-5`} disabled={!connected || busy} onClick={() => setCreating(true)}><Plus size={15} />빈 프로젝트 만들기</button><span className="mt-4 inline-flex items-center gap-1.5 text-xs text-gray-500"><CheckCircle2 size={13} />소스와 이미지가 함께 저장됩니다.</span></div>}
    </div>
  </section>;
}
